### ISSUE TITLE
Too long shebang causing a crash in installing venv-update

### ISSUE THREAD

**Issue by pharaun** [Yelp/venv-update#150]
```
Downloading/unpacking venv-update
  Downloading venv_update-1.1.0-py2.py3-none-any.whl
Downloading/unpacking wheel>0.25.0 (from venv-update)
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB): 66kB downloaded
Requirement already satisfied (use --upgrade to upgrade): pip>=1.5.0,<6.0.0 in /usr/lib/python2.6/dist-packages (from venv-update)
Downloading/unpacking setuptools>=0.8.0 (from venv-update)
  Downloading setuptools-21.0.0-py2.py3-none-any.whl (509kB): 509kB downloaded
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/pymodules/python2.6 (from wheel>0.25.0->venv-update)
Installing collected packages: venv-update, wheel, setuptools
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.6/dist-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/pip/req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.6/dist-packages/pip/req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.6/dist-packages/pip/wheel.py", line 215, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.6/dist-packages/pip/wheel.py", line 209, in clobber
    shutil.copy2(srcfile, destfile)
  File "/usr/lib/python2.6/shutil.py", line 95, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.6/shutil.py", line 51, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.6/dist-packages/pip_faster.py'
```

@bukzor and I was able to debug this error, its basically the shebang being too long, due to a jenkins job name. I was trying to run the venv-update inside a path that was >128 character long.

@bukzor requested me to file a ticket to update/patch venv-update to fail hard in this case so that its at least a bit more obiv in the future what happened.

**Comment by kentwills** [comment]
@bukzor +1, wasted an hour on this today
