### ISSUE TITLE
Tries to create a Python 2.7 (`python`) virtualenv even when not installed

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/venv-update#151]
Can it fall back to `sys.executable` if `python` cannot be found?

```
Step 5 : RUN HOME=/tmp python3 /opt/ocfweb/vendor/venv-update venv= -ppython3 /opt/ocfweb/venv install= /opt/ocfweb -r /opt/ocfweb/requirements.txt
 ---> Running in 9bb5e59a160d
> virtualenv /tmp/.cache/venv-update/1.0.0/venv
The executable python2 (from --python=python2) does not exist
Traceback (most recent call last):
  File "/opt/ocfweb/vendor/venv-update", line 460, in <module>
    exit(main())
  File "/opt/ocfweb/vendor/venv-update", line 455, in main
    exec_scratch_virtualenv(args)
  File "/opt/ocfweb/vendor/venv-update", line 195, in exec_scratch_virtualenv
    run(('virtualenv', scratch.venv))
  File "/opt/ocfweb/vendor/venv-update", line 133, in run
    check_call(cmd)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('virtualenv', '/tmp/.cache/venv-update/1.0.0/venv')' returned non-zero exit status 3
INFO[0002] The command [/bin/sh -c HOME=/tmp python3 /opt/ocfweb/vendor/venv-update venv= -ppython3 /opt/ocfweb/venv install= /opt/ocfweb -r /opt/ocfweb/requirements.txt] returned a non-zero code: 1
```

**Comment by asottile** [comment]
fwiw, this is the vanilla virtualenv behaviour:

```
$ docker run -ti ubuntu:xenial bash -exc 'apt-get update && apt-get install virtualenv --no-install-recommends -y && virtualenv venv'
...
+ virtualenv venv
The executable python2 (from --python=python2) does not exist
```

wontfix?

**Comment by chriskuehl** [comment]
That sounds reasonable to me.
