### ISSUE TITLE
venv-update broken with python3.6

### ISSUE THREAD

**Issue by asottile** [Yelp/venv-update#168]
Looks due to old version of setuptools:

```
# python venv_update.py venv= venv -ppython3.6
> virtualenv /root/.cache/venv-update/1.1.2/venv
New python executable in /root/.cache/venv-update/1.1.2/venv/bin/python
Installing setuptools, pip...done.
> /root/.cache/venv-update/1.1.2/venv/bin/python -m pip.__main__ install virtualenv --target /root/.cache/venv-update/1.1.2/src.tmp
Downloading/unpacking virtualenv
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB): 1.8MB downloaded
Installing collected packages: virtualenv
Successfully installed virtualenv
Cleaning up...
> virtualenv venv -ppython3.6
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /venv/bin/python3.6
Also creating executable in /venv/bin/python
Installing setuptools, pip, wheel...done.
> pip install --find-links=file:///root/.cache/pip-faster/wheelhouse venv-update==1.1.2
Collecting venv-update==1.1.2
  Url 'file:///root/.cache/pip-faster/wheelhouse' is ignored: it is neither a file nor a directory.
  Downloading venv_update-1.1.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=0.8.0 in /venv/lib/python3.6/site-packages (from venv-update==1.1.2)
Collecting pip<6.0.0,>=1.5.5 (from venv-update==1.1.2)
  Url 'file:///root/.cache/pip-faster/wheelhouse' is ignored: it is neither a file nor a directory.
  Downloading pip-1.5.6-py2.py3-none-any.whl (1.0MB)
    100% |################################| 1.0MB 1.5MB/s 
Requirement already satisfied: wheel>0.25.0 in /venv/lib/python3.6/site-packages (from venv-update==1.1.2)
Installing collected packages: pip, venv-update
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-1.5.6 venv-update-1.1.2
> pip-faster install --upgrade --prune -r requirements.txt
Traceback (most recent call last):
  File "/venv/bin/pip-faster", line 7, in <module>
    from pip_faster import main
  File "/venv/lib/python3.6/site-packages/pip_faster.py", line 21, in <module>
    import pip as pipmodule
  File "/venv/lib/python3.6/site-packages/pip/__init__.py", line 9, in <module>
    from pip.log import logger
  File "/venv/lib/python3.6/site-packages/pip/log.py", line 9, in <module>
    from pip._vendor import colorama, pkg_resources
  File "/venv/lib/python3.6/site-packages/pip/_vendor/pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

Something went wrong! Sending 'venv' back in time, so make knows it's invalid.
```

**Comment by asottile** [comment]
I believe this is blocked on upgrading pip.

One could imaging patching out `pip._vendor.pkg_resources` but it gets imported as a side-effect of importing `pip.__init__` so it's too late (unless we did something like or used [pymonkey](https://github.com/asottile/pymonkey))

**Comment by asottile** [comment]
Verified locally this works
