### ISSUE TITLE
"AssertionError: Should be unreachable in pip8+" when installing testing-mysqld instead of testing.mysqld

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/venv-update#202]
```bash
ckuehl@xenialdev1-uswest1cdevc:/tmp/tmp.Iw42OvXnus$ virtualenv -ppython3.6 venv
[...]

ckuehl@xenialdev1-uswest1cdevc:/tmp/tmp.Iw42OvXnus$ venv/bin/pip install --upgrade pip venv-update
Requirement already up-to-date: pip in ./venv/lib/python3.6/site-packages
Collecting venv-update
  Using cached venv_update-2.1.3-py2.py3-none-any.whl
Requirement already up-to-date: wheel>0.25.0 in ./venv/lib/python3.6/site-packages (from venv-update)
Requirement already up-to-date: setuptools>=0.8.0 in ./venv/lib/python3.6/site-packages (from venv-update)
Installing collected packages: venv-update
Successfully installed venv-update-2.1.3

ckuehl@xenialdev1-uswest1cdevc:/tmp/tmp.Iw42OvXnus$ venv/bin/pip-faster install testing-mysqld
Collecting testing-mysqld
  slow: full search for unpinned requirement testing-mysqld
  Using cached testing.mysqld-1.4.0-py2.py3-none-any.whl
Collecting testing.common.database>=1.1.0 (from testing-mysqld)
  slow: full search for unpinned requirement testing.common.database>=1.1.0 (from testing-mysqld)
  Downloading testing.common.database-2.0.1-py2.py3-none-any.whl
Collecting pymysql (from testing-mysqld)
  slow: full search for unpinned requirement pymysql (from testing-mysqld)
  Downloading PyMySQL-0.7.11-py2.py3-none-any.whl (78kB)
    100% |████████████████████████████████| 81kB 7.3MB/s 
Installing collected packages: testing.common.database, pymysql, testing-mysqld
Successfully installed pymysql-0.7.11 testing-mysqld testing.common.database-2.0.1
Exception:
Traceback (most recent call last):
  File "/tmp/tmp.Iw42OvXnus/venv/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/tmp.Iw42OvXnus/venv/lib/python3.6/site-packages/pip_faster.py", line 382, in run
    required = trace_requirements(required)
  File "/tmp/tmp.Iw42OvXnus/venv/lib/python3.6/site-packages/pip_faster.py", line 308, in trace_requirements
    assert dist is not None, 'Should be unreachable in pip8+'
AssertionError: Should be unreachable in pip8+
```

If I install `testing.mysqld` instead of `testing-mysqld`, it works fine. Vanilla pip is okay with either.

https://github.com/tk0miya/testing.mysqld is the project being installed.

**Comment by asottile** [comment]
[Here's where I changed this last](https://github.com/Yelp/venv-update/pull/170/files#diff-19cb1e6086332629ba95070bde7cda1bR294)

**Comment by chriskuehl** [comment]
@solarkennedy ran into this with `backports-functools-lru-cache==1.4` (same traceback, nothing really useful in it). Tracing with pdb, the problem is here:

```python
dist = working_set.find(_package_req_to_pkg_resources_req(req.req))
```

...is getting `None`. Something's up with name normalization:

```python
(Pdb) p req.req
<Requirement('backports-functools-lru-cache==1.4')>
(Pdb) p working_set.find(pkg_resources.Requirement.parse(str('backports-functools-lru-cache==1.4')))
None
(Pdb) p working_set.find(pkg_resources.Requirement.parse(str('backports.functools-lru-cache==1.4')))
backports.functools-lru-cache 1.4 (/nail/home/ckuehl/proj/py-gitolite/.tox/py27/lib/python2.7/site-packages)
```

Similar to the testing.mysqld workaround, it also is sufficient to switch from `backports-functools-lru-cache` to `backports.functools-lru-cache` in the requirements.
