### ISSUE TITLE
Does not work on Windows with python 3.6

### ISSUE THREAD

**Issue by axnsan12** [Yelp/venv-update#206]
`pip-faster` fails to install any package, both in and outside a virtualenv.
I get this error:

```text
Collecting djangorestframework>=3.7.3
  slow: full search for unpinned requirement djangorestframework>=3.7.3
  Using cached djangorestframework-3.7.3-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "c:\projects\{project}\.tox\py36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\projects\{project}\.tox\py36\lib\site-packages\pip_faster.py", line 365, in run
    options, args,
  File "c:\projects\{project}\.tox\py36\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "c:\projects\{project}\.tox\py36\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\projects\{project}\.tox\py36\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\projects\{project}\.tox\py36\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\projects\{project}\.tox\py36\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "c:\projects\{project}\.tox\py36\lib\site-packages\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "c:\projects\{project}\.tox\py36\lib\site-packages\pip_faster.py", line 190, in pipfaster_download_http_url
    _store_wheel_in_cache(file_path, index_url)
  File "c:\projects\{project}\.tox\py36\lib\site-packages\pip_faster.py", line 161, in _store_wheel_in_cache
    mkdirp(cache_dir)
  File "c:\projects\{project}\.tox\py36\lib\site-packages\pip_faster.py", line 150, in mkdirp
    os.makedirs(pth)
  File "c:\projects\{project}\.tox\py36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "c:\projects\{project}\.tox\py36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "c:\projects\{project}\.tox\py36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\{user}/.cache\\pip-faster\\wheelhouse\\https:'
```

**Comment by asottile** [comment]
This is almost certainly due to our use of the index url (which contains `:`) in the cache paths.  We'd probably need to refactor that to support windows.

**Comment by axnsan12** [comment]
Would stripping all path-unsafe characters from the cache key be enough?

Also, from a quick glance, would the following two lines suffice?

https://github.com/Yelp/venv-update/blob/c8732161dda5ba7ff6588577bad21fd50423af7d/pip_faster.py#L86
https://github.com/Yelp/venv-update/blob/c8732161dda5ba7ff6588577bad21fd50423af7d/pip_faster.py#L159

**Comment by asottile** [comment]
Probably? Hard to say without trying it :)

If we're going to do that, we should probably only strip path-invalid characters on platforms that don't support them (for maximum compatibility with the current release on posix platforms).
